apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: golang-hpa
  namespace: autonomos
  labels:
    AppName: golang
spec:
  scaleTargetRef:
    kind: Deployment
    name: golang-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50